server:
  port: 8081

spring:
  application:
    name: USERSERVICE
  datasource:
   driver-class-name: com.mysql.jdbc.Driver 
   url: jdbc:mysql://localhost:3306/userservice
   username: ${DB_USERNAME}
   password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-2021577.okta.com/oauth2/default
          jwk-set-uri: https://integrator-2021577.okta.com/oauth2/default/v1/keys

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client-credentials
            scope: internal
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
        provider:
          okta:
            issuer-uri: https://integrator-2021577.okta.com/oauth2/default



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch_registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
